### ISSUE TITLE
SUSHI Config should support referring to profiles (and etc) by name/id

### ISSUE THREAD

**Issue by cmoesel** [FHIR/sushi#1018]
There are bits of `sushi-config.yaml` that require the author to supply a full or partial URL referring to a resource in the IG.  For example:

```yaml
global:
  Patient: http://example.org/fhir/StructureDefinition/my-patient-profile
  Encounter: http://example.org/fhir/StructureDefinition/my-encounter-profile

resources:
  Patient/my-example-patient:
    name: My Example Patient
    description: An example Patient
    exampleBoolean: true
  Patient/bad-example: omit

groups:
  GroupA:
    name: Group A
    description: The Alpha Group
    resources:
    - StructureDefinition/animal-patient
    - StructureDefinition/arm-procedure
  GroupB:
    name: Group B
    description: The Beta Group
    resources:
    - StructureDefinition/bark-control
    - StructureDefinition/bee-sting
```

It would be more user-friendly if SUSHI allowed you to use the resource names (or ids) as you have defined them in the IG.  If this was allowed, then the examples above might look like this:

```yaml
global:
  Patient: MyPatientProfile
  Encounter: MyEncounterProfile

resources:
  my-example-patient:
    name: My Example Patient
    description: An example Patient
    exampleBoolean: true
  bad-example: omit

groups:
  GroupA:
    name: Group A
    description: The Alpha Group
    resources:
    - AnimalPatient
    - ArmProcedure
  GroupB:
    name: Group B
    description: The Beta Group
    resources:
    - BarkControl
    - BeeSting
```

Of course, the names should be uniquely identifiable.  If a name used could resolve to more than one thing in the IG, then the more complete form would need to be used.
