### ISSUE TITLE
SUSHI Config Groups doesn't handle groups without resources

### ISSUE THREAD

**Issue by cmoesel** [FHIR/sushi#1019]
SUSHI allows groups to be defined in sush-config.yaml without resource, like this:
```yaml
groups:
  Group A: My Group A
  Group B: My Group B
```
or with resources, like this:
```yaml
groups:
  GroupA:
    name: Group A
    description: My Group A
    resources:
    - StructureDefinition/ProfileA1
    - StructureDefinition/ProfileA2
  GroupB:
    name: Group B
    description: My Group B
    resources:
    - StructureDefinition/ProfileB1
    - StructureDefinition/ProfileBA2
```

If you use the latter format, but don't provide resources, SUSHI issues an error. E.g.:
```yaml
groups:
  GroupA:
    name: Group A
    description: My Group A
  GroupB:
    name: Group B
    description: My Group B
```
results in:
> error SUSHI encountered the following unexpected error: group.resources is not iterable

Ideally, SUSHI should be able to handle this and just process the group name and description without any resources.
