### ISSUE TITLE
SUSHI crashes if you try to put extensions on pages in sushi-config.yaml

### ISSUE THREAD

**Issue by cmoesel** [FHIR/sushi#1094]
Apparently you can put FMM status on pages in an IG.  If you try to do this, however, SUSHI crashes and prints out a usage statement.

To reproduce, add this in your `sushi-config.yaml`:
```yaml
pages:
  index.md:
    title: Example Home
    extension:
      - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
        valueCode: trial-use
      - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm
        valueInteger: 3
```

If you run SUSHI, it will crash.  If you delete or comment out the extension parts, it runs fine.

Expected behavior: Generate an IG JSON with those extensions at `ImplementationGuide.definition.page[0].extension`.

See: https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/FMM.20and.20standards.20status/near/284475473
