### ISSUE TITLE
SUSHI does not properly encode menu item names

### ISSUE THREAD

**Issue by cmoesel** [FHIR/sushi#1097]
Including something like this in `sushi-config.yaml`'s `menu` causes problems:
```yaml
Specification:
    Measures: measures.html
    Plans & Interventions: interventions.html
    Conformance & Workflow: workflow.html
```
The problem is that `&` needs to be encoded to `&amp;` in the XML menu.

If we fix SUSHI to do this encoding, we need to be careful not to double-encode items that were already encoded by the user.

See: https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/Menu.20issue/near/285404188
