### ISSUE TITLE
Support Menu Items w/ Links AND Sub-Items

### ISSUE THREAD

**Issue by cmoesel** [FHIR/sushi#1336]
Currently, a menu item can either be a link OR it can have sub-items. At the time we implemented this, that was all that the templates supported. The FHIR team, however, is working on improving support so an item can have a link AND sub-items. Once this is implemented, SUSHI should support this as well.

To support this, SUSHI will have to support an alternate menu format in sushi-config.yaml. For example... given the current menu format like this:
```yaml
menu:
  Home:
    Purpose: 'purpose.html'
    How to:
      Part 1: 'part1.html'
      Part 2: 'part2.html'
```
If we wanted to support links for `Home` and `How to`, we might want to support a format like this:
```yaml
menu:
  Home:
    - index.html
    - Purpose: 'purpose.html'
    - How to:
      - 'howto_overview.html'
      - part 1: 'part1.html'
      - part 2: 'part2.html'
```
or make everything a list like this:
```yaml
menu:
  - Home:
    - index.html
    - Purpose: 'purpose.html'
    - How to:
      - 'howto_overview.html'
      - part 1: 'part1.html'
      - part 2: 'part2.html'
```
See: https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/Menu
