### ISSUE TITLE
SUSHI should allow wildcard directory paths in the path-resource parameter

### ISSUE THREAD

**Issue by jafeltra** [FHIR/sushi#1415]
It appears that the IG publisher allows using a directory wildcard `/*` in the `path-resource` parameter. However, SUSHI does not.

In SUSHI, you can list out the path to each subfolder to include, but trying to include multiple directories with a `/*` at the end does not work. For example, you need to do something like this:

```yaml
parameters:
  path-resource:
    - input/resources/group1
    - input/resources/group2
```

rather than something like

```yaml
parameters:
  path-resource:
    - input/resources/*
```

A small project that replicates the issue: [NestedFolders.zip](https://github.com/FHIR/sushi/files/13993751/NestedFolders.zip)

Zulip: https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/sub-folder.20support
