### ISSUE TITLE
Consider New Grammar for Deeply Nested Paths

### ISSUE THREAD

**Issue by markkramerus** [FHIR/sushi#291]
While FSH is very good at expressing profiling rules, the current path grammar is cumbersome for populating arrays and nested arrays with fixed values. An example is creating Questionnaires, which often have deep nesting.  In this and similar situations, YAML is much more concise. Embedding YAML documents in FSH is under consideration. A YAML document begins with `---` and ends with `...`. Here's an example of a questionnaire defined in FSH with an embedded YAML document:

```
Instance: MyQuestionnaire
InstanceOf: Questionnaire
Description: "An example of embedded YAML"
* code = NL#VL1118-651.2.2 "Lifelines Questionnaire 1 part 1"
---
item:
  - linkId: '1'
    text: Do you have allergies?
    type: boolean
  - linkId: '2'
    text: General questions
    type: group
    item:
      - linkId: '2.1'
        text: What is your gender?
        type: string
      - linkId: '2.2'
        text: What is your date of birth?
        type: date
      - linkId: '2.3'
        text: What is your country of birth?
        type: string
      - linkId: '2.4'
        text: What is your marital status?
        type: string
  - linkId: '3'
    text: Intoxications
    type: group
    item:
      - linkId: '3.1'
        text: Do you smoke?
        type: boolean
      - linkId: '3.2'
        text: Do you drink alchohol?
        type: boolean
...

**Comment by cmoesel** [comment]
If you drop into YAML, are you giving up all FSH syntax (for codes, quantities, references, etc)? Or is it really just an alternate way of writing the paths (and using `:` instead of `=` since it is YAML)?

I assume you're proposing this for instances only? (At least for now)?

**Comment by rdingwell** [comment]
This probably falls inline with some of Chris's questioning but at what level would yaml be allowed?  For instance if I did this:  
```
---
Instance: MyQuestionnaire
InstanceOf: Questionnaire
Description:  An example of embedded YAML
...
```
Would that be possible or are there places where yaml would not be allowed?

**Comment by dwwinters** [comment]
I like the idea of a more compact notation for Questionnaire instances.  I do wonder if the YAML may be harder to follow for  Questionnaires with lots of extensions and/or items of type choice.  For instance, I took the example that  @markkramerus posted and made it a little more complicated (did not verify that this is 100% correct):
```
Instance: MyQuestionnaire
InstanceOf: Questionnaire
Description: "An example of embedded YAML"
* code = NL#VL1118-651.2.2 "Lifelines Questionnaire 1 part 1"
---
item:
  - linkId: '1'
    extension:
      - url: http://hl7.org/fhir/StructureDefinition/designNote
        valueMarkdown: "Implement as a radio button"
    text: Do you have allergies?
    type: choice
    answerOptions:
      - valueString: 'Yes'
        extension:
          - url: http://hl7.org/fhir/StructureDefinition/ordinalValue
            valueDecimal: 1
      - valueString: 'No'
        extension:
          - url: http://hl7.org/fhir/StructureDefinition/ordinalValue
            valueDecimal: 0
  - linkId: '2'
    text: General questions
    type: group
    item:
      - linkId: '2.1'
        text: What is your sex at birth?
        type: choice
        answerOption:
          - valueCoding:
              system: http://terminology.hl7.org/CodeSystem/v3-AdministrativeGender
              code: F
              display: Female
          - valueCoding:
              system: http://terminology.hl7.org/CodeSystem/v3-AdministrativeGender
              code: M
              display: Male
          - valueCoding:
              system: http://terminology.hl7.org/CodeSystem/v3-NullFlavor
              code: UNK
              display: Unknown
      - linkId: '2.2'
        extension:
          - url: http://hl7.org/fhir/StructureDefinition/designNote
            valueMarkdown: "Please ensure an accessible date picker is used."
        text: What is your date of birth?
        type: date
      - linkId: '2.3'
        text: What is your country of birth?
        type: choice
        answerValueSet: '#countryCodes'
      - linkId: '2.4'
        text: What is your marital status?
        type: choice
        answerValueSet: '#maritalStatusCodes'
  - linkId: '3'
    text: Intoxications
    type: group
    item:
      - linkId: '3.1'
        text: Do you smoke?
        type: choice
        answerOptions:
          - valueString: 'Yes'
            extension:
              - url: http://hl7.org/fhir/StructureDefinition/ordinalValue
                valueDecimal: 1
          - valueString: 'No'
            extension:
              - url: http://hl7.org/fhir/StructureDefinition/ordinalValue
                valueDecimal: 0
      - linkId: '3.2'
        text: Do you drink alchohol?
        type: choice
        answerOption:
          - valueString: 'Yes'
            extension:
              - url: http://hl7.org/fhir/StructureDefinition/ordinalValue
                valueDecimal: 1
          - valueString: 'No'
            extension:
              - url: http://hl7.org/fhir/StructureDefinition/ordinalValue
                valueDecimal: 0
...
```
