### ISSUE TITLE
SUSHI stops running when a YAML error is encountered

### ISSUE THREAD

**Issue by jafeltra** [FHIR/sushi#437]
This was initially reported on Zulip here: https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/SUSHI.200.2E13.2E0-beta.2E1/near/197713853.

To recreate this, add the following into `config.yaml`: 

```
parameters:
  show-inherited-invariants: true
  special-url: http://www.genenames.org/geneId
  special-url: http://glstring.org
```

SUSHI stops running without giving any error messages.
