### ISSUE TITLE
Consider supporting additional menu features

### ISSUE THREAD

**Issue by cmoesel** [FHIR/sushi#440]
Two common features of IG menus are:
* ability to launch in a new tab
* indicator for external web site

We could potentially support them via keywords like this:
```yaml
menu:
  Home: index.md
  FHIR Spec: external new-tab {{site.data.fhir.path}}index.html
```

Before we implement this, however, we should probably decide if the "menu" feature in the config.yaml beta will make it through to the mainline release.

See: https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/SUSHI.200.2E13.2E0-beta.2E1/near/197489659
