### ISSUE TITLE
Config.yaml should allow dependency URLs to be specified

### ISSUE THREAD

**Issue by cmoesel** [FHIR/sushi#497]
Apparently some packages do not have a canonical URL in the IG JSON (or maybe they have no IG JSON at all?) -- but ImplementationGuide requires a uri be specfied for every dependency.  To support this, the config.yaml needs to allow authors to manually specify a URI for a dependency (since SUSHI cannot automatically find it).

See: https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/Packages.20with.20no.20canonical

This also seems like a good opportunity to give the user control over the dependency `id` field if they want it.

To implement this, we should support the value of `dependencies.[packageId]` to be a `string` (as it is now, which represents the version) _or_ an object, with keys for `id`, `uri`, and `version`. 

E.g., this:
```yaml
dependencies:
  hl7.fhir.us.core: 3.1.0
```
is exactly the same as this:
```yaml
dependencies:
  hl7.fhir.us.core:
    version: 3.1.0
```
Although you usually would only use that longer form when you want to specify additional properties:
```yaml
dependencies:
  hl7.fhir.us.core:
    id: uscore
    uri: http://hl7.org/fhir/us/core/ImplementationGuide/hl7.fhir.us.core
    version: 3.1.0
```

Part of this task would also include adding an error to help guide the user when SUSHI can't find an IG URL on its own.  E.g., if the author has this:
```yaml
dependencies:
  nictiz.fhir.nl.stu3.zib2017: 1.3.10
```
then SUSHI won't be able to find a canonical URL for it.  I think it already returns an error in this case, but now the error should suggest the user specify the URL in the config.yaml dependencies if this is a package with no official canonical URL (and it should probably give an example of what that might look like).
